spring.application.name=sbservice
monitoring.memory.interval=10000
monitoring.processor.interval=10000
monitoring.resources.interval=10000

# Export Custom Monitor metrics to Graphite
graphite.custom.enabled = true

# Export metrics to Graphite
management.graphite.metrics.export.enabled=false

# Connection to Graphite service
management.graphite.metrics.export.host=localhost
management.graphite.metrics.export.port=2003
management.graphite.metrics.export.protocol=PLAINTEXT
# Metrics to Graphite interval
management.graphite.metrics.export.step=1000

# Prefix for Graphite metrics
#management.graphite.metrics.export.prefix=sbservice
management.metrics.tags.app-prefix=${spring.application.name}
management.graphite.metrics.export.tags-as-prefix=app-prefix